//= Using Peer-to-Peer Sync (websockets)
//:page-layout: article
//:page-status: {release-status-cbl} -- {release-comments-cbl}
//:page-edition: Enterprise
//:page-role:
//
//include::partial$_std-cbl-hdr-{param-module}.adoc[]
//
// BEGIN::Local page attributes
//
//:url-issues-java: {url-github-cbl}{module}/issues
//:ziputils: {snippets-pfx--android}/code_snippets/ZipUtils.java
//

[abstract]
--
{description}
{param-abstract}
--

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--

DOC-6340-H2-P2P: New topic - Implementing P2P Sync
https://issues.couchbase.com/browse/DOC-6340

This is the how-to for P2P snc using websockets
--
endif::[]

== Overview

ifeval::["{page-edition}"=="{enterprise}"]
.Enterprise Edition only
IMPORTANT: Peer-to-peer sync is an {url-enterprise} feature.
You must purchase the Enterprise License which includes official {url-support-policy} to use it in production (also see the {url-license-and-supp-faq}).
endif::[]

This content provides sample code covering the implementation of peer-to-peer sync over websockets. Specifically it covers the implementation of an active peer listener, that will sync database changes with a connected passive peer.

=== Discovery
Optional, but typical step.

Prior to connecting with a listener you may execute a peer discovery phase.
For the active peer this involves browsing-for and selecting the appropriate service using a zero-config protocol such as _Bonjour_.

Alternatively if the listener is configured to use a known endpoint then the client can instead be pre-configured to connect to the listener.

// image::ROOT:replication.svg[,800]


== Establish Connection

.Simple Replication to Listener
====

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="p2p-act-rep-func"]
----

<1> A replication is an asynchronous operation.
Keep a reference to the `replicator` object by setting it as an instance property.
<2> Construct the listener endpoint from its IP, Port and Database name and use the `URLEndpoint` to initialize a connection with the target.
<3> The URL scheme for remote database URLs uses `ws:` (non-TLS) or `wss:` (SSL/TLS) prefixes.
<4> Use the `ReplicationConfiguration` classes `init(database:target:)` constructor to initialze the replication configuration set.
<5> The `ServerCertificateVerificationMode` can be: `caCert` (default) or `selfSignedCert`.
====


== Initialize Peer Connection

Initialize the replication connection, providing the target (passive peer's) endpoint details, whether pre-configured or gathered during a discovery phase.

The required elements comprise:

* The passive peer's URL as returned fron the discovery phase
* The port the listener is listening on
* The database to be sync'd
You need to append the target database name to the url.

You will also need any security credentials provided (for example, user name and password or Cert) for use in authentication.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="p2p-act-rep-initialize"]
----

=== Configure

Configure the required replication options. For more on these see: {xref-cbl-pg-replicaton}.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="p2p-act-rep-config"]
----

=== Authenticate

Configure the authenticator to be used to authenticate the

ion mode, for example 'self signed certificate'

Authentication modes available include:

* Basic
* Client CA
* Self-signed Cert

Set the authenticator, for example `BasicAuthenticator` and provides the current users credentials

This example shows basic authentication using user name and password:

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="p2p-act-rep-auth"]
----

=== Server Authentication

Configure the server authentication mode using `ServerCertificateVerificationMode`.

Valid options are:
caCert::
Verify by using trusted anchor CA certs or by using the configured pinned server certs (Default Mode).
selfSignedCert::
 Verify by accepting any and only self-signed certs. Any non-self-signed certs will be rejected.

== Listen for Changes

Add a change listener as a callback to the Replicator.

You will then be asynchronously notified of state changes.
Use this to monitor changes and to inform on sync progress, as shown below; this is an optional step.

// Add change listener
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-act-rep-add-change-listener,indent=0]
----

Use the `replicator.status` property to monitor the status of a replication.
That is, when it is actively transferring data and when it has stopped.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-act-rep-status,indent=0]
----

The status struct comprises the following elements:

* activity -- stopped, offline, connecting, idle or busy
* progress
** completed The total number of changes completed
** total -- the total number of changes to be processed
* error -- the current error, if any

For more on replication status, see: {xref-cbl-pg-replication--status}

API Reference::
{url-api-property-replication-status}
{url-api-method-add-change-listener}

