//= Using Peer-to-Peer Sync (websockets)
//:page-layout: article
//:page-status: {release-status-cbl} -- {release-comments-cbl}
//:page-edition: Enterprise
//:page-role:
//
//include::partial$_std-cbl-hdr-{param-module}.adoc[]
//
// BEGIN::Local page attributes
//
//:url-issues-java: {url-github-cbl}{module}/issues
//:ziputils: {snippets-pfx--android}/code_snippets/ZipUtils.java
//

[abstract]
--
{description}
{param-abstract}
--

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--

DOC-6340-H2-P2P: New topic - Implementing P2P Sync
https://issues.couchbase.com/browse/DOC-6340

This is the how-to for P2P snc using websockets
--
endif::[]

== Overview

ifeval::["{page-edition}"=="{enterprise}"]
.Enterprise Edition only
IMPORTANT: Peer-to-peer sync is an {url-enterprise} feature.
You must purchase the Enterprise License which includes official {url-support-policy} to use it in production (also see the {url-license-and-supp-faq}).
endif::[]

This content provides sample code covering the implementation of peer-to-peer sync over websockets. Specifically it covers the implementation of a passive peer listener, that will accept and apply database changes replicated by a connected active peer.

=== Discovery
Optional, but typical step.

Pior to initiating the listener you may execute the peer discovery phase.
For the passive peer this involves advertising the device using, for example _Bonjour_, and waiting for an invite.
The connection is established once the passive peer has authenticated and accepted an active peer's invitation.

//[#pass-initialize]
//====
// include::{snippet-p2psync-ws}[tags="startWebsocketsListener"]
//[source, {source-language}]
//----
//include::{snippet-p2psync-ws}[tags="listener-config"]
//----
//====

=== Initialization

[#simple-listener-initialization]
.Simple Listener Initialization
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-initialize", indent=0]
----

<1> <<configure-listener>>
<2> <<configure-tls-authentication>>
<3> <<configure-client-authentication>>
<4> <<configure-delta-sync>>
<5> Initialize the listener using the configuration settings
<6> Start the listener
<7> <<conflict-resolution>>
====

== Configure Listener

Use a combination of the two `URLEndointListenerConfiguration` constructors (below) to set the <<Database>>, <<Port>> and <<network-interface,IP>> to be used.

* `public init(database: Database)`
* `init(config:)`


=== Database
API Reference: {url-api-reference-urlendpointconfiguration-initdb}

Using the `init(database)` constructor, as in <<simple-listener-initialization>> this example, will initialize the configuration paramaters with details of the local database endpoint.
All other configuration values will take their default setting.

NOTE: Database is read-only, and can only be set using this constructor.

=== Port

Use this configuration parameter to specify the port that the listener will listen to.
If this is null or zero, the port is auto-assigned.

Default::
Null or zero depending on platform.
Example::
+
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-port", indent=0]
----
API::
{url-api-reference-urlendpointconfiguration-port}

=== Network Interface

Use this configuration parameter to specify the network interface the listener is to listen on.
Specify either an IP Address or network interface name such as `en0`

Default:: nil -- the listener will listen to all network interfaces
Example::
+
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-netw-iface", indent=0]
----
API::
* {url-api-reference-urlendpointconfiguration-netwk-iface}


== Configure TLS Authentication

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-pv-cfg-tls-auth", indent=0]
----

== Configure Client Authentication

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-pv-cfg-client-auth", indent=0]
----


== Configure Delta Sync

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-pv-cfg-delta-sync", indent=0]
----


== Configure Conflict Resolver

The listener returns a 409 response on detecting a conflict.
All conflicts are reolved on the active peer, which supports both  automatic and custom conflict resolution.

// [source, {source-language}]
// ----
// include::{snippet-p2psync-ws}[tags="listener-pv-cfg-conflict", indent=0]
// ----

//[#pass-start]
== Start Listener

The first step after connection establishment on the passive peer is to initialize and start a new _WebsocketEndpointListener_, passing it the remote peer and database contexts.

This tells the listener to accept incoming data from that peer.
//====
// include::{snippet-p2psync-ws}[tags="initWebsocketsListener"]
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-pv-start-listener", indent=0]
----
//====

At this point the _active peer_ will initiate a replication. When the replication is complete, the active peer will
 initiate disconnection.

== Checking the Status

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-pv-status-check", indent=0]
----

== Disconnection

Stop the Listener on receipt of the disconnect.
//====
// include::{snippet-p2psync-ws}[tags="stopWebsocketsListener"]config
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-pv-stop-listener"]
----


== Using Authentication

[{tabs}]
====
Basic -- User/Password::
+
--
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-auth-basic-pwd"]
----
--

TLS -- Self-signed::
+
--
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-auth-basic-self-signed"]
----
--

TLS - Cert Auth (Roots)::
+
--

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-auth-tls-CCA-Root-full", indent=0]
----
--

TLS -- Cert Auth::
+
--

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-auth-tls-ca-cert", indent=0]
----
--
====