//= Using Peer-to-Peer Sync (websockets)
//:page-layout: article
//:page-status: {release-status-cbl} -- {release-comments-cbl}
//:page-edition: Enterprise
//:page-role:
//
//include::partial$_std-cbl-hdr-{param-module}.adoc[]
//
// BEGIN::Local page attributes
//
//:url-issues-java: {url-github-cbl}{module}/issues
//:ziputils: {snippets-pfx--android}/code_snippets/ZipUtils.java
//

// DONE: TODO:  Replace the throw ListDocError. in all code snippets to be a comment // throw appropriate exception

// ifeval::["{page-edition}"=="Enterprise"]
// .Enterprise Edition only
// IMPORTANT: This an {url-enterprise} feature.
// Purchase the _Enterprise License_, which includes official {url-support-policy}, to use it in production (see the license and support {url-license-and-supp-faq}).
// endif::[]

[abstract]
{description}
{param-abstract}

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--

DOC-6340-H2-P2P: New topic - Implementing P2P Sync
https://issues.couchbase.com/browse/DOC-6340

This is the how-to for P2P snc using websockets
--
endif::[]

[.pane__frames]
== Overview

[.no-title.no-color]
.{empty}
* {empty}
+
--
This content provides sample code covering the implementation of {glos-term-peer-to-peer-sync} over websockets. Specifically it covers the implementation of a {glos-term-passive-peer} listener, that will accept and apply database changes replicated by a connected active peer.

In the context of this content the term _client_ refers to the _active peer_ and the term _server_ to the _passive peer_

You will need to initialize and configure a listener for each Couchbase Lite database instance that you want to sync with other peers.

The <<simple-listener-initialization>> example below shows a simple initialization and configuration process.

The subsequent sections show additional details on the configuration options with examples. You do not need to provide configuration values for all properties, only those necessary to meet the requirements of your sync process.
--

[.narrow]
.Key concepts
* {url-api-references}[API Reference]
* {xref-cbl-pg-p2psync-websocket}

[.no-title]

== {empty}

[#simple-listener-initialization]
.Simple Listener Initialization
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-initialize", indent=0]
----

<1> <<initialize-the-listener>>
<2> <<configure-server-security>>
<3> <<configure-client-security>>
<4> <<configure-delta-sync>>
<5> Initialize the listener using the configuration settings
<6> Start the listener
<7> <<conflict-resolution>>
====


== Discovery
An optional, but typical step.

Prior to initiating the listener you may execute the peer discovery phase or use a pre-configured endpoint.

For the passive peer discovery involves advertising the service using, for example _Bonjour_, and waiting for an invite from the {glos-term-active-peer}.
The connection is established once the passive peer has authenticated and accepted an active peer's invitation.

//[#pass-initialize]
//====
// include::{snippet-p2psync-ws}[tags="startWebsocketsListener"]
//[source, {source-language}]
//----
//include::{snippet-p2psync-ws}[tags="listener-config"]
//----
//====

== Initialize the Listener

You will need to initialize a listener for each Couchbase Lite database instance that you want to sync with other peers.

Use the `URLEndpointListenerConfiguration` constructor `public init(database: Database)` to set the end point of the database. This will comprise <<Database>>, <<Port>> and <<network-interface,IP>>.

=== Database

Property name::
`database:`

Description::
+
--
Using the `init(database)` constructor, as in <<simple-listener-initialization>> this example, will initialize the configuration parameters with details of the local database endpoint.
All other configuration values will take their default setting.

NOTE: Database is read-only, and can only be set using this constructor.
--
Default::
Mandatory
Example::
See callout 1 in <<simple-listener-initialization>>
API Reference::
{url-api-reference-urlendpointconfiguration-initdb} |
{url-api-reference-urlendpointconfiguration-database}

=== Port
Property name::
`port`

Description::
+
Use this configuration parameter to specify the port that the listener will listen to.
If this is null or zero, the port is auto-assigned.

Default::
Null or zero depending on platform.

Example::
+
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-port", indent=0]
----

API Reference::
{url-api-reference-urlendpointconfiguration-port}

=== Network Interface

Property name::
`networkInterface`

Description::
+
--
Use this configuration parameter to specify the network interface the listener is to listen on.
Specify either an IP Address or network interface name such as `en0`
--

Default:: nil -- the listener will listen to all network interfaces

Example::
+
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-netw-iface", indent=0]
----
API Reference::
{url-api-reference-urlendpointconfiguration-netwk-iface}

//== Configure the Listener

// <<configure-tls>>
// | <<configure-client-authentication>>
// | <<configure-delta-sync>>
// | <<conflict-resolution>>

== Configure Server Security
// DONE: TODO: Move under top level security section
_In this section_:
<<enable-or-disable-tls,Use TLS>>
| <<configure-tls-server-identity, Set the TLS Identity>>
| back to: <<simple-listener-initialization>>

=== Enable or Disable TLS

Property name::
`disableTLS`

Description::
+
--
include::{root-partials}p2p-api.adoc[tag=config-disable-tls]
--

Default::
include::{root-partials}p2p-api.adoc[tag=config-disable-tls-default]

Example::
+
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-disable-tls", indent=0]
----

API Reference::
{url-api-reference-urlendpointconfiguration-disable-tls}

=== Configure TLS Server Identity

Property name::
`tlsIdentity`

Description::
+
--
Use this property to set the required TLS Server identity.

Typically, you will configure the TLS Server identity once during initial launch.
Subsequent starts of the listener will then reuse the identity from the keychain, or (re)create it if it doesn't exist.

include::{root-partials}p2p-api.adoc[tag=config-tls-id]
--

Default::
include::{root-partials}p2p-api.adoc[tag=config-tls-id-default]

Example::
{empty}
+
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-tls-id", indent=0]
----

API Reference::
{url-api-reference-urlendpointconfiguration-tls-id}

Related-items::
{url-api-reference-tlsidentity}

== Configure Client Security
// DONE: TODO: Moove to top level security section.
_In this section_:
<<authenticate-using-the-client-username-and-password>>
| <<authenticate-using-the-client-certificate>>
| <<the-impact-of-tls-settings>>
// | <<expected-system-behavior>>
| back to: <<simple-listener-initialization>>

[pass]
---

Use the
{url-api-class-urlendpointconfiguration} class's {url-api-reference-urlendpointconfiguration-auth} property to specify how client credentials are to be authenticated.

Valid options are:

* ListenerPasswordAuthenticator -- which authenticates using a client's username and password
* ListenerCertificateAuthenticator -- which authenticates using  a clients certificate.

// include::{root-partials}p2p-api.adoc[tag=config-auth]

=== Authenticate Using the Client Username and Password

This content shows how to authenticate using the client username and password. For how authenticate using client certs see: <<authenticating-with-certificate>>

include::{root-partials}p2p-api.adoc[tag=ListenerPasswordAuthenticator]

include::{root-partials}p2p-api.adoc[tag=ListenerPasswordAuthenticatorDelegate]

.Password authentication
====
In this example, `allowlistedUsers` is a dictionary comprising the usernames and passwords of valid users. Credentials not in `allowlistedUsers` are denied access.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=listener-config-auth, indent=0]
----
====

=== Authenticate using the Client Certificate

include::{root-partials}p2p-api.adoc[tag=ListenerCertificateAuthenticator]

==== Using Root CA Certificate Chains

include::{root-partials}p2p-api.adoc[tag=ListenerCertificateAuthenticator-root]

==== Using Application Logic

include::{root-partials}p2p-api.adoc[tag=ListenerCertificateAuthenticatorDelegate]

// Examples::

// [{tabs}]
// ====

// Password authentication::
// +
// --
// In this example, `allowlistedUsers` is a dictionary comprising the usernames and passwords of valid users. Credentials not in `allowlistedUsers` are denied access.

// [source, {source-language}]
// ----
// include::{snippet-p2psync-ws}[tags=listener-config-auth, indent=0]
// ----
// --

// Root cert authentication::
// +
// --
// [source, {source-language}]
// ----
// include::{snippet-p2psync-ws}[tags="listener-config-client-auth-root", indent=0]
// ----
// --

// Cert authentication::
// +
// --
// [source, {source-language}]
// ----
// include::{snippet-p2psync-ws}[tags="listener-config-client-auth-self-signed", indent=0]
// ----
// --

// ====

=== The Impact of TLS Settings

The table in this section shows the expected system behavior (in regards to security ) depending on the TLS configuration settings deployed.

.Expected system behavior
[cols="12,44,44"]
|===
|`disableTLS` |`tlsIdentity` (corresponding to server) |Expected system behavior

|true
|Ignored
a|. TLS is disabled.
. Communication is plain text.

|false
| set to `nil`
a|. The system will auto generate an _anonymous_ self signed cert.
.  Active peers will skip validation of the server cert.
. Communication is encrypted

|false
a|Set to server identity generated from a self- or CA-signed certificate

// On first use::
* On first use -- Bring your own cert and private key (use `importIdentity`).
* Each time -- Use the server identity from the cert stored in the keychain; for example, use `TSLIdentity.identity(withIdentity:)`.

See: {xref-cbl-pg-p2p-manage-tls-id} for more on how to store and use identities.

a|. System will use the provided self- or CA-signed cert.
. Active peers will validate the cert.
. Communication is encrypted.

// |false
// a|
// // Use the convenience `createIdentity` API to generate the cert and identity
// * On first use -- Bring your own CA cert and private key (use `importIdentity`).
// * Each time -- Use the server identity from the CA cert stored in the keychain; for example, use `TSLIdentity.identity(withIdentity:)`.

// See: {xref-cbl-pg-p2p-manage-tls-id} for more on how to store and use identities.
// a|. The system will use the provided CA cert.
// . Active peers will validate the CA cert.
// . Communication is encrypted.

|===

== Configure Delta Sync
back to: <<simple-listener-initialization>>

Property name::
{url-api-reference-urlendpointconfiguration-delta-sync}

Description::
+
--
Use the `enableDeltaSync` property to activate or deactivate delta sync mode when replicating.
--

Default::
False -- delta sync is not allowed in replication.

Example::
+
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-delta-sync", indent=0]
----

API Reference::
{url-api-reference-urlendpointconfiguration-delta-sync}


//[#pass-start]
== Start Listener

Once you have configured the listener, you can start listening, ready to accept incoming data from active peers.
//====
// include::{snippet-p2psync-ws}[tags="initWebsocketsListener"]
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-start", indent=0]
----
//====

== Check the Status

You can use the `status` property of the listener to check on the number of total and active connections.
The object returned is of type `ConnectionStatus` and comprises:

* ConnectionCount -- the total number of connections served by the listener
* activeConnectionCount -- the number of active (BUSY) connections currently being served by the listener

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-status-check", indent=0]
----


== Conflict Resolution

The listener returns a 409 response on detecting a conflict.
All conflicts are resolved on the active peer, which supports both  automatic and custom conflict resolution.

// [source, {source-language}]
// ----
// include::{snippet-p2psync-ws}[tags="listener-pv-cfg-conflict", indent=0]
// ----

== Stop the Listener
//====
// include::{snippet-p2psync-ws}[tags="stopWebsocketsListener"]config
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-stop"]
----
