//= Using Peer-to-Peer Sync (websockets)

include::{root-partials}block-abstract.adoc[]

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--

DOC-6340-H2-P2P: New topic - Implementing P2P Sync
https://issues.couchbase.com/browse/DOC-6340

This is the how-to for P2P snc using websockets
--
endif::[]

== Overview

ifeval::["{page-edition}"=="{enterprise}"]
.Enterprise Edition only
IMPORTANT: Peer-to-peer sync is an {url-enterprise} feature.
You must purchase the Enterprise License which includes official {url-support-policy} to use it in production (also see the {url-license-and-supp-faq}).
endif::[]

This content provides sample code covering the implementation of peer-to-peer sync over websockets. Specifically it covers the implementation of an active peer, that will sync database changes with a connected passive peer.

The code snippet in <<simple-replication-to-listener>> covers the configuration, initialization and replication is expanded upon in subsequent sections in this content.

include::{root-partials}block-code-disclaimer.adoc[]

.Simple Replication to Listener
[#simple-replication-to-listener]
====

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tag=p2p-act-rep-func, indent=0]
----
<.> Use the `ReplicationConfiguration` class's `init(database:target:)` constructor to initialize the replicator configuration with the local database and remote listener endpoint -- see <<configure-target>>

<.> The `ServerCertificateVerificationMode` can be: `.caCert` (default) or `.selfSignedCert`.
Use the `.selfSignedCert` to skip listener cert validation. -- see <<configure-server-security>>.

<.> The `authenticator` mode is configured to use basic auth.
Other supported options are `ClientCertificateAuthenticator` if you want to use client cert based authentication -- see <<configure-client-security>>

<.> Initialize the replicator with specified configuration

<.> Register a observer to be notified of changes to the replication status

<.> Start the replicator
====

== API References

You can find {url-api-references}[{param-title} API References] here.

== Discovery
Optional, but typical step.

Prior to connecting with a listener you may execute a peer discovery phase to dynamically discover peers.
For the active peer this involves browsing-for and selecting the appropriate service using a zero-config protocol such as _Bonjour_.

Alternatively if the listener is configured to use a known endpoint (eg. static IP Address or well known DNS address) then the client can instead be statically pre-configured to connect to the listener at that known endpoint.

// image::ROOT:replication.svg[,800]

== Configure Target

Use the
{url-api-class-replicator-config} class to initialize the replication configuration by the
{url-api-constructor-replicator-config-db-tgt} constructor.

This constructor provides the target (server/passive peer's) endpoint details, whether pre-configured or gathered during a discovery phase, together with the name of the local database to be synced.

The required parameters are:

* Use the {url-api-prop-replicator-config-target} property to specify the passive peer's URL including the port the listener is listening on.
The URL scheme for web socket URLs uses `ws:` (non-TLS) or `wss:` (SSL/TLS) prefixes.

* Use the
{url-api-prop-replicator-config-database} property to specify the local database to be synced.

You will also need any security credentials provided (for example, user name and password or Cert) for use in the authentication phase of configuration.

.Set target and database config properties
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="p2p-act-rep-initialize"]
----
====

== Configure Sync Mode

Use the `{url-api-prop-replicator-config-rep-type}` and
`{url-api-prop-replicator-config-cont}` properties of
`{url-api-class-replicator-config}` to tell the replicator:

* The direction of the replication: `push`; `pushAndPull`; `pull`.
* Whether the replicator should:
** Stay active indefinitely to replicate changed documents: `continuous=true`
** Be a one-shot replication of changed documents: `continuous=false`

.Configure replicator type and mode
====

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-act-rep-config-type, indent=0]
include::{snippet-p2psync-ws}[tags=p2p-act-rep-config-cont, indent=0]
----

====

== Configure Server Security

:this-prop: ServerCertificateVerificationMode

Use the {url-api-prop-replicator-config-ServerCertificateVerificationMode} property to tell the replicator how to verify TLS server certificates.

The valid options at this stage are:

* `selfSignedCert` -- Verify by accepting any (and only) self-signed certs; non-self-signed certs will be rejected
* `caCert` -- Verify by using trusted anchor CA certs or by using the configured pinned server certs.
This is the default mode

See: {url-api-enum-replicator-config-ServerCertificateVerificationMode}

.Example
[{tabs}]
====
selfSignedCert::
+
--
// TODO : Two examples
// Example 1:
// Use .selfsignedcert mode and no pinned cert (This mode ignores the server cert)
// Example 2:
// Use .cacert mode and show pinned cert (pinned cert can be self signed or CA cert)
This examples uses `.selfSignedCert` mode, showing configuration using a self-signed certificate with no pinned cert; that is, the server cert is not validated.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-act-rep-config-self-cert]
----
--
+
caCert::
+
--
This example uses `.cacert` mode and a pinned cert,  which can be either a self- or CA-signed cert.
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tag=p2p-act-rep-config-cacert-pinned, indent=0]
----
--
====

== Configure Client Security

Use the {url-api-prop-replicator-config-auth} property to provide client authentication credentials to the replicator.

Valid options include:

* Use the `{url-api-class-replicator-config-basic-auth}` property to set up basic authentication with the username and password credentials.

* Use the `{url-api-class-replicator-config-cert-auth}` property to configure the client TLS certs to be presented to the server, on connection. This applies only to the {url-api-class-urlendpointlistener}.

If you are using certificates, you have the option to either:

* Use Couchbase Lite's convenience API to create self-signed certificates.
The `{url-api-class-tlsidentity}` class provides methods to manage identities.
* Bring your own certificate.
Our convenience API also gives you the flexibility to bring your own TLS identities, using the `{url-api-method-tls-identity-import}` method.
+
This makes it easy to bundle PKCS12 certificates with your application.

See {xref-cbl-pg-p2p-manage-tls-id} for more on how to do this.


.example
[{tabs}]
====
Basic::
+
--
This example shows basic authentication using user name and password:

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="p2p-act-rep-auth", indent=0]
----
--

Client Cert::
+
--

This example shows client cert authentication using an identity from the keychain.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-tlsid-tlsidentity-with-label, indent=0]
----
--
====

For how to import identities and add them to the keychain see {xref-cbl-pg-p2p-manage-tls-id}

== Initiate Sync

Initialize the replicator using the {url-api-constructor-replicator-init-config} specifying the configuration set you have defined, optionally add a change listener <<monitor-sync>> and start the replicator running using {url-api-method-replicator-start}.

.Initialize and run replicator
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-act-rep-start-full;!p2p-act-rep-add-change-listener, indent=0]
----
====

== Monitor Sync

=== Change Listeners
Use the {url-api-class-replicator} class to add a change listener as a callback to the Replicator ({url-api-method-replicator-add-change-listener}).
You will then be asynchronously notified of state changes.
Use this to monitor changes and to inform on sync progress, as shown below; this is an optional step.

=== Replicator Status
You can also use the {url-api-property-replicator-status} property to monitor replicator status.
That is, when it is actively transferring data and when it has stopped.

The {url-api-class-replicator-status} structure comprises the following elements:

* {url-api-enum-replicator-activity} -- stopped, offline, connecting, idle or busy
* {url-api-enum-replicator-progress}
** completed The total number of changes completed
** total -- the total number of changes to be processed
* {url-api-enum-replicator-error} -- the current error, if any

For more on replication status, see: {xref-cbl-pg-replication--status}

.Example
[{tabs}]
====
addChangeListener()::
+
--
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-act-rep-add-change-listener,indent=0]
----
--
+
replicator.status::
+
--
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-act-rep-status,indent=0]
----
--
====

== Stop Sync

Stopping the replication is straightforward using the r{url-api-method-replicator-stop}
 method.
If you added an optional change listener <<monitor-sync>> you should also remove it using the `removeChangeListener` method.

.Stop replicator
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=p2p-act-rep-stop, indent=0]
----
====


== Conflict Resolution

The default conflict resolver is applied (see {xref-cbl-pg-conflict-auto}) unless you use the {url-api-prop-replicator-config-conflict} property to specify a custom conflict resolver object (see: {xref-cbl-pg-conflict-custom}).

For more on replicator conflict resolution see: {xref-cbl-pg-conflict}.

//TODO: Update example to show how the confog resolver property is set (refer to the stanadrd replicator code)

.Conflict resolving

include::{root-partials}handling-conflicts.adoc[tags=conflict-custom-resolution-examples]


== Delta Sync
// DONE: Add reference to listener section tht oincludes enableDeltaSync property being set to true
If delta sync is enabled on the listener, then replication will use delta sync.

For more on how to:

* Enable delta sync on the listener -- see: {xref-cbl-pg-dbo-p2psync-websocket-using-passive--delta-sync}
* Replicator Delta Sync concept -- see: {xref-cbl-pg-replication--delta-sync}
