//= Using Peer-to-Peer Sync (websockets)

include::{root-partials}block-abstract.adoc[]

ifndef::release-status-cbl[:release-status-cbl!:]
ifeval::["{release-status-cbl}" == "gamma"]
[.pane__frame--orange]
.Author's Notes
--

DOC-6340-H2-P2P: New topic - Implementing P2P Sync
https://issues.couchbase.com/browse/DOC-6340

This is the how-to for P2P snc using websockets
--
endif::[]

== Overview

This content provides sample code covering the implementation of {glos-term-peer-to-peer-sync} over websockets.
Specifically it covers the implementation of a {glos-term-passive-peer} listener, that will accept and apply database changes replicated by a connected {glos-term-active-peer}. In this context the term _client_ refers to the _active peer_ and the term _server_ to the _passive peer_

You will need to initialize and configure a listener for each Couchbase Lite database instance that you want to sync with other peers.

<<simple-listener-initialization>> shows a simple initialization and configuration process.

The subsequent sections show additional details on the configuration options with examples.
You do not need to provide configuration values for all properties, only those necessary to meet the requirements of your sync process.

[#simple-listener-initialization]
.Simple Listener Initialization
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-initialize";!listener-config-tls-id-cert, indent=0]
----
<.> <<configure-listener-endpoint>>
<.> <<configure-tls-security>>
<.> <<configure-client-authentication>>
<.> <<configure-delta-sync>>
<.> Initialize the listener using the configuration settings
<.> <<start-listening>>
<.> On-going listener <<monitor-the-listener, monitoring>>, including <<conflict-resolution>>
====

== API References
You can find {url-api-references}[{param-title} API References] here.

== Device Discovery
*This phase is optional:* If the listener is initialized on a well known URL endpoint (for example, a static IP Address or well known DNS address) then you can configure active peers to connect to those.

Prior to initiating the listener you may execute a peer discovery phase.

For the passive peer, this involves advertising the service using, for example _Bonjour_, and waiting for an invite from the active peer.
The connection is established once the passive peer has authenticated and accepted an active peer's invitation.

== Configure Listener Endpoint

Set the listener endpoint.
As a minimum this must include the local database name.
You can also over-ride the auto-seleted default port number and-or configure a specific network-interface.

All other configuration values will take their default setting.

Database name::
+
--
The database name is set using the mandatory, read-only {url-api-references-urlendpointconfiguration-database} parameter to the `{url-api-class-urlendpointconfiguration}` constructor
//`public init(database: Database)`.
{url-api-references-urlendpointconfiguration-initdb}.
--

Port number::
+
--
The listener will auto-select an available port.

Alternatively, use the {url-api-references-urlendpointconfiguration-port} parameter to specify a known port.

// Example::
// +
// [source, {source-language}]
// ----
// include::{snippet-p2psync-ws}[tags="listener-config-port", indent=0]
// ----
--

Network Interface::
+
--
The listener will listen on all network interfaces.

Alternatively, use
{url-api-references-urlendpointconfiguration-netwk-iface} parameter
to specify the network interface.
This must be either an IP Address or network interface name such as `en0`.
--

.Configure Endpoint
====
In this example `_userDb` has previously been declared as an object of type Database.
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-endpoint", indent=0]
----
====

// Example::
// +
// [source, {source-language}]
// ----
// include::{snippet-p2psync-ws}[tags="listener-config-netw-iface", indent=0]
// ----


//== Configure the Listener

// <<configure-tls>>
// | <<configure-client-authentication>>
// | <<configure-delta-sync>>
// | <<conflict-resolution>>

== Configure TLS Security
// DONE: TODO: Move under top level security section
// _In this section_:
// <<enable-or-disable-tls,Use TLS>>
// | <<configure-tls-server-identity, Set the TLS Identity>>
// | back to: <<simple-listener-initialization>>

Enable or Disable TLS::
+
--
include::{root-partials}p2p-api.adoc[tag=config-disable-tls]
--

Set TLS Server Id::
+
--
include::{root-partials}p2p-api.adoc[tag=config-tls-id]

Typically, you will configure the TLS Server identity once during initial launch.
Subsequent starts of the listener will then reuse the identity from the keychain, or (re)create it if it doesn't exist -- see: {xref-cbl-pg-p2p-manage-tls-id}

--
// include::{snippet-p2psync-ws}[tags="listener-config-tls-id-cert", indent=0]
// include::{snippet-p2psync-ws}[tags="listener-config-tls-id-cert", indent=0]
// include::{snippet-p2psync-ws}[tags="listener-config-tls-id-full,!createTlsIdentity,!retrieveTlsIdentity,!listener-config-tls-id-cert", indent=0]

[#1]
.Set TLS server identity
[{tabs}]
====

Use Anonymous Certificate::
+
--
Use “anonymous” certificate.
These are self signed certificates created by the system.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-tls-id-nil,!listener-config-tls-id-cert", indent=0]
----
--

Retrieve TLS Identity to Use::
+
--
This examples retrieves a TLS identity previously stored in the {securestorage} using its alias.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-tls-id-full,!listener-config-tls-id-nil,!createTlsIdentity", indent=0]
----
--

Create TLS Identity to Use::
+
--
This example creates a new identity using a set of credentials. It stores the identity in the {securestorage} and then adds the identity to the listener's configuration.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-tls-id-full,!listener-config-tls-id-nil,!retrieveTlsIdentity", indent=0]
----
--

====

== Configure Client Authentication
// DONE: TODO: Move to top level security section.

Use the
{url-api-class-urlendpointconfiguration} class's {url-api-references-urlendpointconfiguration-auth} parameter to specify how client credentials are to be authenticated.

Valid options are:

* ListenerPasswordAuthenticator -- which authenticates using a client's username and password
* ListenerCertificateAuthenticator -- which authenticates using  a clients certificate.

// include::{root-partials}p2p-api.adoc[tag=config-auth]

=== Authenticate Using the Client Username and Password

This section shows how to authenticate client username and password using basic authentication.
For how to authenticate using client certs see: <<authenticating-with-certificate>>

include::{root-partials}p2p-api.adoc[tag=ListenerPasswordAuthenticator]

include::{root-partials}p2p-api.adoc[tag=ListenerPasswordAuthenticatorDelegate]

.Password authentication
====
In this example, `allowlistedUsers` is a dictionary comprising the usernames and passwords of valid users. Credentials not in `allowlistedUsers` are denied access.

[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags=listener-config-auth, indent=0]
----
====


=== Authenticate using the Client Certificate

--
include::{root-partials}p2p-api.adoc[tag=ListenerCertificateAuthenticator]
--

include::{root-partials}p2p-api.adoc[tag=ListenerCertificateAuthenticator-root]

include::{root-partials}p2p-api.adoc[tag=ListenerCertificateAuthenticatorDelegate]

.Set Cert Auth
[{tabs}]
====
Using Root CA Certificate Chains::
+
--
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-client-auth-root", indent=0]
----
--
+
Using Application Logic::
+
--
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-client-auth-self-signed", indent=0]
----
--
====

=== The Impact of TLS Settings

The table in this section shows the expected system behavior (in regards to security ) depending on the TLS configuration settings deployed.

.Expected system behavior
[cols="12,44,44"]
|===
|`disableTLS` |`tlsIdentity` (corresponding to server) |Expected system behavior

|true
|Ignored
a|. TLS is disabled.
. Communication is plain text.

|false
| set to `nil`
a|. The system will auto generate an _anonymous_ self signed cert.
.  Active peers will skip validation of the server cert.
. Communication is encrypted

|false
a|Set to server identity generated from a self- or CA-signed certificate

// On first use::
* On first use -- Bring your own cert and private key (use `importIdentity`).
* Each time -- Use the server identity from the cert stored in the keychain; for example, use `TSLIdentity.identity(withIdentity:)`.

See: {xref-cbl-pg-p2p-manage-tls-id} for more on how to store and use identities.

a|* System will use the configured identity.
* Active peers will validate the server cert corresponding to the TLSIdenity (as long as they are configured to not skip validation -- see <<configure-tls-security>>.

// |false
// a|
// // Use the convenience `createIdentity` API to generate the cert and identity
// * On first use -- Bring your own CA cert and private key (use `importIdentity`).
// * Each time -- Use the server identity from the CA cert stored in the keychain; for example, use `TSLIdentity.identity(withIdentity:)`.

// See: {xref-cbl-pg-p2p-manage-tls-id} for more on how to store and use identities.
// a|. The system will use the provided CA cert.
// . Active peers will validate the CA cert.
// . Communication is encrypted.

|===

== Configure Delta Sync

Delta sync replication is not enabled by default.

Use the `{url-api-references-urlendpointconfiguration-delta-sync}` parameter of `{url-api-class-urlendpointconfiguration}` to activate or deactivate delta sync mode when replicating.

.Enable delta sync
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-config-delta-sync", indent=0]
----
====

== Start Listening

Once you have completed the listener's configuration settings you can initialize the listener instance and start listening -- see: <<initialize-and-start-listener>>


[#initialize-and-start-listener]
.Initialize and start listener
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-start", indent=0]
----
<.> Initialize the listener instance using the configuration settings.
<.> Start the listener, ready to accept connections and incoming data from active peers.
<.> Start and required on-going listener <<monitor-the-listener, Monitoring>>, including <<conflict-resolution>>
====

== Monitor the Listener

You can use the `status` parameter of the listener to check on the number of total and active connections.
The object returned is of type `ConnectionStatus` and comprises:

* ConnectionCount -- the total number of connections served by the listener
* activeConnectionCount -- the number of active (BUSY) connections currently being served by the listener

.Using status to monitor listener
====
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-status-check", indent=0]
----
====

== Conflict Resolution

All conflicts are resolved on the active peer, which supports both automatic and custom conflict resolution.
The listener returns a 409 response on detecting a conflict.

// [source, {source-language}]
// ----
// include::{snippet-p2psync-ws}[tags="listener-pv-cfg-conflict", indent=0]
// ----

== Stop the Listener
====
// include::{snippet-p2psync-ws}[tags="stopWebsocketsListener"]config
.Stop listening using `stop` method
[source, {source-language}]
----
include::{snippet-p2psync-ws}[tags="listener-stop", indent=0]
----
====
