// BEGIN -- inclusion -- database-load-prebuilt.adoc - Used in {commons-}database.adoc file

== Use case

As a mobile application developer I want to minimize any wait time that a user may experience on initial install and launch of my application -- for example, due to initialization and data setup.

== Solution

Include a pre-built version of any required database(s) in your application bundle.

It is typically more efficient to download bulk data using the http/ftp stream  employed during the application installation than to install a smaller application bundle and then have to use a replicator to pull-in the bulk data.

Couchbase Lite makes it easy to bundle pre-built databases as application resources.
You can then deploy them on initial launch making for a smoother user experience.
The initial sync of any pre-built database will pull-in any content changes on the server that occurred after its incorporation into the app, quickly bringing the database up to date.

== In use

To use a prebuilt database, you need to:

* Set up the a new Couchbase Lite database
* Incorporate that database into your app bundle as a resource -- see <<inc-db>>
* Adjust your start-up logic to deploy the packaged database if it doesn't exist and to then initiate a sync to update it -- see <<deploy-db>>

[#inc-db]
== Bundle Database with Application

In your build and release process:

. Create a fresh Couchbase Lite database (every time) +
Always start with a fresh database for each app version to ensure there are no checkpoint issues
+
NOTE: If you don't do this, and instead reuse the same database in your build process (for subsequent app versions), then you will invalidate the cached checkpoint in the packaged database.
. Pull your Sync Gateway database into the new Couchbase Lite database +
Use either the REST API, or the cblite tool (`cblite cp`), for this +
Ensure the replication uses the exact same URL and parameters as those your app will use when it is running
+
NOTE: If this replication and the in-app replications don't use exactly the same parameters (for example, the URL or channels don’t match), then the checkpoint IDs will not match
. When the replication is complete, create the same indexes the app will use
. Copy the database into your app package +
Put it in an appropriate place (for example, a resource folder).
Where possible you can zip the database.


[#deploy-db]
== Deploy Database on Initial Launch

During the application start-up logic, check if database exists in the required location, and *if not*:

. Locate the pre-packaged database (for example, in the assets or other resource  folder)
. Copy the pre-packaged database to the required database location +
Use {url-api-method-database-copy} to do this, to ensure that a UUID is generated for each copy
+
[source, {source-language}]
----
include::{snippet}[tag=prebuilt-database,indent=0]
----
+
NOTE: Copying the database manually will not generate a new UUID, so each copy of the app will invalidate the others’ checkpoints
. Open the database
. Start a pull replication, to sync any changes  +
The replicator uses the pre-built database's checkpoint as the timestamp to sync from; only documents changed since then are synced
. Do not wait for replication to complete if you can avoid it +
Start your normal application logic immediately, unless it is essential to have the absolute up-to-date data set to begin.
That way the user is not kept hanging around watching a progress indicator.
They can begin interacting with your app whilst any out-of-data data is being updated.

// END -- inclusion -- database-load-prebuilt.adoc - Used in {commons-}database.adoc file
